id: A195B8B22
title: Poṣadhasthāpanavastu
type: translation
source_metadata:
  languages:
  - bo
  datatype: PlainText
  created_at: 2022-03-01 22:20:38.903582
  last_modified_at: 2022-03-01 22:20:38.903613
